# Generated by Django 5.1.5 on 2025-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aiquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('course_douration', models.IntegerField()),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
